### ISSUE TITLE
Update README Instructions

### ISSUE THREAD

**Issue by JakeVestal** [DukeAML/FML#4]
I noticed that on the recent branch, there exist both an environment.prod.ts and an environment.ts file in the frontend. If that's a fix to the need to ask the user to rename, then please update the instructions in the README

**Comment by JakeVestal** [comment]
When I clone fresh and run the app, I don't need to do anything with environment files (everything works with no renaming). Therefore I'm asking: is it still necessary to instruct the user to do anything at all with regard to renaming files?

**Comment by jaiveerk** [comment]
Hm, that's unusual... usually Angular looks for that file to set environment variables (like credentials or setting it to debug or production mode), so it shouldn't be working without the environment.ts file (we had this issue earlier on and needed to add that file).

It's in our gitignore, but I wonder if the first time you cloned the repo was before we added it there, so you always had the file and later versions of the repo, it never got deleted since we eventually added it to the gitignore
